### ISSUE TITLE
Cppvsdbg not working

### ISSUE THREAD

**Issue by guestieng** [webewildered/scriptpoints#1]
This extension looks like a nice approach.
However, unfortunately it does not seem to work with Visual C++ debugger (compare also the [vscode-cpptools issue on cppvsdbg ](https://github.com/microsoft/vscode-cpptools/issues/2591#issuecomment-771991122)).
At least I could not get it working.

**Comment by maaberne-havok** [comment]
Hey @guestieng thanks for giving it a try!  Could I ask for a bit more information:
- which version of the extension did you test?
- what were your logpoint messages?
- does the debugger pause when it hits your breakpoints with scripts?
- can you check if any expressions you're evaluating work when pasted into the watch window?

I've also been using this extension with msvc and cppvsdbg, so I'm interested to see what's wrong.

**Comment by guestieng** [comment]
Ok, I did not use the latest version(s), indeed.
After updating it's working now.
Thank you very much!
